<?php
require __DIR__.'/../includes/bootstrap.php'; require_admin(); $pdo=db();
$leadId=(int)($_GET['lead_id']??$_POST['lead_id']??0); $s=$pdo->prepare('SELECT * FROM leads WHERE id=? AND status="Closed_Won"'); $s->execute([$leadId]); $lead=$s->fetch();
if(!$lead){ header('Location: index.php?tab=leads'); exit; }
$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!verify_csrf()) $error='Phiên làm việc không hợp lệ.';
    else { $buyer=trim($_POST['company_name_buyer']??''); $price=(float)($_POST['final_price']??0); $details=trim($_POST['contract_details']??''); $status=$_POST['status']??'Draft';
        if($buyer===''||$price<=0||$details===''||!in_array($status,['Draft','Signed'],true)) $error='Vui lòng nhập đủ công ty/người mua, giá chốt và điều khoản.';
        else { $pdo->prepare('INSERT INTO contracts(lead_id,company_name_buyer,final_price,contract_details,status) VALUES(?,?,?,?,?)')->execute([$leadId,$buyer,$price,$details,$status]); $id=(int)$pdo->lastInsertId(); header('Location: contract_print.php?id='.$id); exit; }
    }
}
?><!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Tạo hợp đồng</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"></head><body class="bg-light"><main class="container py-5" style="max-width:850px"><a href="index.php?tab=leads" class="text-decoration-none">← Quay lại leads</a><h1 class="h3 mt-3">Tạo hợp đồng</h1><div class="card mt-3"><div class="card-body p-4"><div class="alert alert-light border"><strong>Khách hàng:</strong> <?=e($lead['fullname'])?> · <?=e($lead['phone'])?><br><strong>Loại web:</strong> <?=e($lead['service_type'])?></div><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif?><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="lead_id" value="<?=$leadId?>"><div class="mb-3"><label class="form-label">Tên công ty / người mua</label><input required name="company_name_buyer" class="form-control"></div><div class="mb-3"><label class="form-label">Giá đã chốt (VNĐ)</label><input required min="1" name="final_price" type="number" class="form-control"></div><div class="mb-3"><label class="form-label">Nội dung thỏa thuận</label><textarea required name="contract_details" class="form-control" rows="8" placeholder="Phạm vi công việc, tiến độ, thanh toán, bảo hành..."></textarea></div><div class="mb-4"><label class="form-label">Trạng thái</label><select name="status" class="form-select"><option value="Draft">Bản nháp</option><option value="Signed">Đã ký</option></select></div><button class="btn btn-primary">Tạo và xem bản in</button></form></div></div></main></body></html>
